import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from '../store/providers/ReduxProvider';
import { QueryProvider } from '../store/providers/QueryProvider';
import { CustomThemeProvider } from '../store/providers/ThemeProvider';
import { Header } from '../components/modals';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomThemeProvider>
          <ReduxProvider>
            <QueryProvider>
              <Header />
              {children}
            </QueryProvider>
          </ReduxProvider>
        </CustomThemeProvider> 
      </body>
    </html>
  );
}
